# Generated by Django 2.1.7 on 2019-03-27 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotifyInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('errortype', models.CharField(choices=[('Person', '人员违规信息'), ('Car', '车辆违规信息'), ('Other', '其他违规信息')], max_length=20)),
                ('dealvalue', models.CharField(choices=[('Y', '已处理'), ('T', '处理中'), ('N', '未处理')], max_length=20)),
                ('createTime', models.DateTimeField(auto_now_add=True)),
                ('changeTime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=50)),
                ('ppassword', models.CharField(max_length=20)),
                ('pinstitute', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SafeUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=50)),
                ('spassword', models.CharField(max_length=20)),
                ('sinstitute', models.CharField(max_length=50)),
                ('p', models.ForeignKey(on_delete='id', to='engineer.Pic')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wengineer_name', models.CharField(max_length=50)),
                ('wengineer_num', models.CharField(max_length=50)),
                ('wlinkman', models.CharField(max_length=50)),
                ('wphone', models.CharField(max_length=12)),
            ],
        ),
        migrations.AddField(
            model_name='notifyinfo',
            name='s',
            field=models.ForeignKey(on_delete='id', to='engineer.SafeUser'),
        ),
        migrations.AddField(
            model_name='notifyinfo',
            name='w',
            field=models.ForeignKey(on_delete='id', to='engineer.Work'),
        ),
    ]
